spring:
  application:
    name: auth-service
server:
  port: 8090
jwt:
  tokens:
    access-token: UIERJODHFNTGVIORKDJNLFV8EGERFUJNHDS9IBESRFDCJNV4HKIULCONI984EQKWFMDCEWI894KLFMNCE
    refresh-token: UIERJODHFNTGVIORKDJNLFV8EGERFUJNHDS9IBESRFDCJNV4HKIULCONI984EQKWFMDCEWI894KLFMNCE
  issuer: akerke