version: '3.8'

services:
  voting-service:
    build:
      context: voting-service
      dockerfile: ../docker/dockerfile-voting-service
    ports:
      - "8080:8080"
    environment:
      'spring.kafka.producer.bootstrap-servers': kafka:29092
      'spring.kafka.consumer.bootstrap-servers': kafka:29092
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/votingdb
    depends_on:
      - mongo
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "LISTENER_INTERNAL"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: